---
language: ruby
rvm:
- 1.8.7
- 1.9.3
branches:
  only:
  - master
env:
  matrix:
  - PUPPET_VERSION=2.7.26
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.7.1
notifications:
  email: false
gemfile: Gemfile
